"""content_items: scope slug uniqueness to (kind, slug)

Revision ID: 016da48286e6
Revises: 96f1df56124c
Create Date: 2026-09-15 16:40:54.026064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016da48286e6'
down_revision: Union[str, None] = '96f1df56124c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_items_slug', table_name='content_items')
    op.create_index(op.f('ix_content_items_slug'), 'content_items', ['slug'], unique=False)
    op.create_unique_constraint('uq_content_items_kind_slug', 'content_items', ['kind', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_content_items_kind_slug', 'content_items', type_='unique')
    op.drop_index(op.f('ix_content_items_slug'), table_name='content_items')
    op.create_index('ix_content_items_slug', 'content_items', ['slug'], unique=True)
    # ### end Alembic commands ###
